name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      USERNAME: Jordan   # ðŸ‘ˆ HERE

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print parameter
        run: echo "Username is $USERNAME"

      - name: Compile Java
        run: javac Hello.java

      - name: Run Java program
        run: java Hello

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-class
          path: Hello.class
